from app.llm.base import BaseLLMProvider


class MockLLMProvider(BaseLLMProvider):
    """Mock provider for local development and testing."""

    async def generate(
        self,
        prompt: str,
        system_prompt: str | None = None,
    ) -> str:
        return (
            "Mock response generated by the "
            "AI Software Engineering Agent Platform."
        )